version: '3'
services:
  bus-app.postgres:
    container_name: bus-app.postgres
    image: "postgres"
    ports:
    - 5432:5432
    environment:
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"

